### ISSUE TITLE
Inject event names into documentation for reference

### ISSUE THREAD

**Issue by garthk** [coryodaniel/notion#3]
From my manual docs:

```markdown
* `[:opencensus, :honeycomb, :start]` before sending
* `[:opencensus, :honeycomb, :stop, :success]` after sending successfully
* `[:opencensus, :honeycomb, :stop, :failure]` after sending unsuccessfully
```

Might be as easy as emitting the [`t:event_name/0`](https://hexdocs.pm/telemetry/telemetry.html#type-event_name) and the first line from the `@doc`. Where to put it, though… in the `@doc` for `events/0` (`event_names/0` if #1) might be the easiest. Either that, or you define a module attribute in the macro and get people to `use Notion` before their `@moduledoc` if they want it in an `## Events` section up there? I wouldn't know for sure until I tried it.

**Comment by coryodaniel** [comment]
I like this.

**Comment by coryodaniel** [comment]
This is possible. I'm going to add it to `events/0` and I'll write up a better "`@moduledoc`" for modules using notion and interpolate the event list into that block of text.

**Comment by coryodaniel** [comment]
https://github.com/coryodaniel/notion/commit/ab22d4ca4a1879d01d6e3b83a0969484cc4cfab2
