### ISSUE TITLE
Discuss: labels

### ISSUE THREAD

**Issue by garthk** [coryodaniel/notion#7]
Something feeling more wrong the more I play with #6 is the magic in `labels`. I reckon injecting those to indicate `%{env: "prod"}` etc is a job better performed by event _handling_ packages like [Telemetry.Metrics](https://hex.pm/packages/telemetry_metrics) than by event _sending_ packages. Amongst other things, it concentrates the opinions about what labels are important into one piece of code or configuration that you control.

(Exploring the converse: if we want every package to call `:telemetry.execute/𝑛` with useful measurements and metadata, which we do, _and_ the responsibility for adding Prometheus-style labels to the metadata was the job of event senders, then you'd end up trying to express those opinions via every dependency you took. Feels somewhere between awkward and outright impossible, to me.)

I'll take @arkgil's [comment here](https://elixirforum.com/t/telemetry-dynamic-dispatching-library-for-metrics-and-instrumentations-v0-3-0-released/19058/7) as more evidence that we want the weight of translating from `:telemetry` to other systems to be put on the packages implementing that translation, but I'll tag him in so he can correct me.

Like #1, if your design intent is to be strongly opinionated about Notion being a Prometheus-optimised `:telemetry` package, let me know and I'll express all these strong opinions elsewhere. :)

**Comment by coryodaniel** [comment]
https://github.com/coryodaniel/notion/commit/ab22d4ca4a1879d01d6e3b83a0969484cc4cfab2
